providers:
  docker: {}
  file:
    filename: /etc/traefik/dynamic_conf.yaml
    watch: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: charley.geoffroy@protonmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web
